version: "3.3"

services:
  db:
    container_name: db
    image: postgres:13.3
    restart: always
    environment: 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile.production
    depends_on: 
      - db
    command: npm test
