version: "3.3"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: npm start

  caddy:
    image: caddy:2.3.0
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes: 
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    depends_on: 
      - app
        

volumes:
  caddy_data:
  caddy_config: