version: "3.3"

services:
  db:
    image: postgres
    env_file: 
      - .env
    environment: 
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
      POSTGRES_USER: ${NODOS_DB_USERNAME}
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    depends_on: 
      - db
    command: npm test
        
