version: "3.3"

services:
  db:
    image: postgres
    restart: always
    env_file: 
      - .env
    environment: 
      POSTGRES_PASSWORD: NODOS_DB_PASSWORD
      POSTGRES_USER: NODOS_DB_USERNAME
  app:
    build: .
    depends_on: 
      - db
