name: push

on:
  push:
    branches:
      - 'master'
      - 'main'

env:
  APP_IMAGE_NAME: deepsick/devops-for-programmers-project-lvl1

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install deps
        run: |
          npm install
        env:
          CI: true

      - name: Run tests
        run: |
          npm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest